[build]
  command = "npm run build"
  publish = "build/"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
